import type { Species } from "@/lib/evoverses/types";

const currentGroup = 3;

export type EvoAnimationProgress = {
  id: number
  species: Species
  idle: boolean
  attack: boolean
  special: boolean
  dash: boolean
  backUp: boolean
  hit: boolean
  death: boolean
}

export const groups: Species[][] = [
  [ "Tamandu", "Skycyx" ],
  [ "Ruard", "Dhaek", "Nythe", "Struthor", "Geckaiba" ],
  [ "Shazark", "Sunopendra", "Hikarul", "Aubelyon", "Kaos" ],
  [ "Onydae", "Mobyd", "Ghorgon", "Nymphel", "Cyarabat" ],
  [ "Eulocelus", "Venuserpien", "Methyst", "Tytan", "Moffunap" ],
  [ "Nissel", "Finantis", "Carcoid", "Allacrow", "Fayde" ],
  [ "Karoite", "Nuvea", "Ainepolux", "Morphee", "Vulpyro" ],
  [ "Hodeon", "Kitsul", "Rattuos", "Tokaleaf", "Flint" ],
  [ "Lumi", "Droserace", "Clocarstone", "Fugush", "Obsy" ],
  [ "Gwenbee", "Uzumebach", "Metheo", "Meissa", "Athel" ],
  [ "Mellio", "Ryomizu", "Beldar", "Lounn", "Fluozacil" ],
  [ "Kapryno", "Firemon", "Kerval", "Espyke", "Gemarites" ],
  [ "Arnoriel", "Adhamandra", "Obryos", "Krokon", "Yotnar" ],
  [ "Jokull", "Caerthos", "Istral", "Cyzorak", "Lamphal", "Sauderon" ],
];

export const inProgress: Species[] = groups[currentGroup];

export const data: EvoAnimationProgress[] = [
  {
    id: 1,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Nissel",
  },
  {
    id: 2,
    idle: true,
    attack: true,
    dash: false,
    backUp: false,
    hit: true,
    death: false,
    special: false,
    species: "Finantis",
  },
  {
    id: 3,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Karoite",
  },
  {
    id: 4,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Nuvea",
  },
  {
    id: 5,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Hodeon",
  },
  {
    id: 6,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Eulocelus",
  },
  {
    id: 7,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Arnoriel",
  },
  {
    id: 9,
    idle: true,
    attack: true,
    dash: false,
    backUp: true,
    hit: true,
    death: true,
    special: false,
    species: "Carcoid",
  },
  {
    id: 10,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Adhamandra",
  },
  {
    id: 11,
    idle: true,
    attack: false,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: true,
    species: "Ainepolux",
  },
  {
    id: 12,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Kapryno",
  },
  {
    id: 13,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Kitsul",
  },
  {
    id: 15,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Rattuos",
  },
  {
    id: 16,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Beldar",
  },
  {
    id: 19,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Firemon",
  },
  {
    id: 20,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Obryos",
  },
  {
    id: 22,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Lumi",
  },
  {
    id: 25,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Onydae",
  },
  {
    id: 26,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Skycyx",
  },
  {
    id: 28,
    idle: true,
    attack: true,
    dash: false,
    backUp: true,
    hit: false,
    death: false,
    special: false,
    species: "Droserace",
  },
  {
    id: 30,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Kerval",
  },
  {
    id: 33,
    idle: true,
    attack: false,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: true,
    species: "Gwenbee",
  },
  {
    id: 34,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Shazark",
  },
  {
    id: 35,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Krokon",
  },
  {
    id: 37,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Clocarstone",
  },
  {
    id: 39,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Tokaleaf",
  },
  {
    id: 40,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Sunopendra",
  },
  {
    id: 42,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Yotnar",
  },
  {
    id: 43,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Hikarul",
  },
  {
    id: 45,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Aubelyon",
  },
  {
    id: 46,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Flint",
  },
  {
    id: 48,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Venuserpien",
  },
  {
    id: 50,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Espyke",
  },
  {
    id: 51,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Mobyd",
  },
  {
    id: 53,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Ghorgon",
  },
  {
    id: 54,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Mellio",
  },
  {
    id: 55,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Fugush",
  },
  {
    id: 56,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Morphee",
  },
  {
    id: 59,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: true,
    species: "Lounn",
  },
  {
    id: 61,
    idle: true,
    attack: true,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: false,
    species: "Uzumebach",
  },
  {
    id: 63,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Gemarites",
  },
  {
    id: 64,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Methyst",
  },
  {
    id: 66,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Tamandu",
  },
  {
    id: 68,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Tytan",
  },
  {
    id: 69,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Moffunap",
  },
  {
    id: 70,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Nymphel",
  },
  {
    id: 75,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Allacrow",
  },
  {
    id: 77,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Jokull",
  },
  {
    id: 78,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: true,
    species: "Vulpyro",
  },
  {
    id: 81,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Fayde",
  },
  {
    id: 83,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Ruard",
  },
  {
    id: 84,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Caerthos",
  },
  {
    id: 85,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Ryomizu",
  },
  {
    id: 86,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Obsy",
  },
  {
    id: 89,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Dhaek",
  },
  {
    id: 91,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Metheo",
  },
  {
    id: 93,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Nythe",
  },
  {
    id: 96,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Meissa",
  },
  {
    id: 97,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Fluozacil",
  },
  {
    id: 100,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Cyarabat",
  },
  {
    id: 102,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Struthor",
  },
  {
    id: 103,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Istral",
  },
  {
    id: 106,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Cyzorak",
  },
  {
    id: 109,
    idle: true,
    attack: false,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: true,
    species: "Kaos",
  },
  {
    id: 117,
    idle: true,
    attack: false,
    dash: true,
    backUp: true,
    hit: true,
    death: false,
    special: true,
    species: "Athel",
  },
  {
    id: 120,
    idle: true,
    attack: false,
    dash: false,
    backUp: false,
    hit: true,
    death: false,
    special: true,
    species: "Lamphal",
  },
  {
    id: 122,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Geckaiba",
  },
  {
    id: 125,
    idle: false,
    attack: false,
    dash: false,
    backUp: false,
    hit: false,
    death: false,
    special: false,
    species: "Sauderon",
  },
].map(e => {
  if (groups.indexOf(groups.find(g => g.includes(e.species as Species))!) < currentGroup) {
    return {
      ...e,
      idle: true,
      attack: true,
      dash: true,
      backUp: true,
      hit: true,
      death: true,
      special: true,
    } as EvoAnimationProgress;
  }
  return e as EvoAnimationProgress;
});
