CREATE
DATABASE squid;
CREATE
USER squid WITH ENCRYPTED PASSWORD '<PASSWORD>';
GRANT ALL PRIVILEGES ON DATABASE
squid TO squid;
GRANT USAGE ON SCHEMA
public TO squid;
GRANT ALL PRIVILEGES ON ALL
TABLES IN SCHEMA public TO squid;
GRANT ALL PRIVILEGES ON ALL
SEQUENCES IN SCHEMA public TO squid;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO squid;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO squid;
ALTER
SCHEMA public OWNER TO squid;
