services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb
    volumes:
      - "./data:/var/lib/postgresql/data"
